#!/bin/bash
echo "count of all arguments:$#"
echo "all variables passed to the script:$@"
echo "all variables passed  to the script:$*"

echo "current working directory:$PWD"
echo "who is running this:$USER"

echo "pid of the script:$$"

sleep 20 &

echo "pid of the last command:$!"


